test: use storage_udevadm_trigger, gather debug when fail
Use `storage_udevadm_trigger: true` which seems to fix some
test failures.

Gather lots of debug information when get_unused_disks fails.

Signed-off-by: Rich Megginson <rmeggins@redhat.com>

diff --git a/tests/tasks/cleanup.yml b/tests/tasks/cleanup.yml
--- a/tests/tasks/cleanup.yml
+++ b/tests/tasks/cleanup.yml
@@ -8,6 +8,7 @@
   include_role:
     name: fedora.linux_system_roles.storage
   vars:
+    storage_udevadm_trigger: true  # helps with get_unused_disks, cleanup
     storage_safe_mode: false
     storage_pools: |
       {% set cleanup_pools = [] %}
@@ -47,6 +48,22 @@
     vgs --all
     cat /tmp/snapshot_role.log || :
     cat /etc/lvm/devices/system.devices || :
+    for dev in $(lsblk -l -p -o NAME); do
+      if [ "$dev" = NAME ]; then continue; fi
+      echo blkid info with cache
+      blkid "$dev" || :
+      echo blkid info without cache
+      blkid -p "$dev" || :
+    done
+    # garbage collect
+    blkid -g || :
+    echo lsblk after garbage collect
+    lsblk -p --pairs --bytes -o NAME,TYPE,SIZE,FSTYPE
+    # flush cache
+    blkid -s none || :
+    echo lsblk after cache flush
+    lsblk -p --pairs --bytes -o NAME,TYPE,SIZE,FSTYPE
+    cat /tmp/blivet.log || :
   changed_when: false
   when: unused_disks_before != unused_disks_return.disks
   failed_when: unused_disks_before != unused_disks_return.disks
